name: Deploy React Frontend to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name pushpaacr.azurecr.io

    - name: Build and push Docker image
      run: |
        docker build -t pushpaacr.azurecr.io/rule:latest .
        docker push pushpaacr.azurecr.io/rule:latest

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group dhanaaaa --name pushpaAks
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
        #